export default Object.freeze({
  ABOUT: "About",
  ACCOUNT: "Account",
  BAR: "My Bar",
  COCKTAIL_ME: "Cocktail Me",
  COCKTAILS_NAVIGATOR: "Cocktails",
  COCKTAILS_SCREEN: "Cocktails Screen",
  COCKTAIL_DETAILS: "Cocktail Details",
  FAVORITES: "Favorites",
  FORGOT_PASSWORD: "Reset your password",
  INTRO: "Intro",
  VALIDATE_TOKEN: "Validate Code",
  INGREDIENT_DETAILS: "Ingredient Details",
  LOGIN: "Login",
  MARKET: "Market",
  REGISTER: "Sign Up",
  RESET_PASSWORD: "Reset password",
  SUCCESS_RESET: "Success!",
  WELCOME: "Welcome",
});
